[package]
name = "cpuset"
version = "0.1.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
log = "0.4.8"
failure = "0.1.7"
simplelog = "0.7.5"
regex = "1.3.7"
